version: '3.8'
services:
  db_main:
    image: mysql:5.7.22
    restart: always
    container_name: db_main
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306
    networks:
      - app-lab
      
  backend_main:
    container_name: backend_main
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    networks:
      - app-lab
    depends_on:
      - db_main
  
  queue_main:
    container_name: queue_main
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    networks:
      - app-lab
    depends_on:
      - db_main

networks:
  app-lab:
    external: true
