version: '3.8'
services:
  db_admin:
    image: mysql:5.7.22
    restart: always
    container_name: db_admin
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306
    networks:
      - app-lab

  backend_admin:
    container_name: backend_admin
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    networks:
      - app-lab
    depends_on:
      - db_admin

  queue_admin: 
    container_name: queue_admin
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    networks:
      - app-lab
    depends_on:
      - db_admin

networks:
  app-lab:
    external: true